Wits-SG/Demeter

src/routes/(signin)/login/+page.svelte
src/routes/(signin)/login/+server.ts
src/routes/(signin)/signup/+page.svelte
src/routes/(signin)/signup/+server.ts

Add user signup via password and email

User Sign Up

---

src/routes/(app)/+page.server.ts
src/routes/(app)/+page.svelte

changed the amount of posts that load.
fixed sql statment logic for the amount of posts loading.

Fix feeds load bug

---

src/lib/components/small_recipe.svelte
src/routes/(app)/cookbook/+page.svelte
src/routes/(app)/cookbook/[cookbook_id]/+page.svelte
src/routes/api/cookbook/recipe/+server.ts

UI fixes and got refresh of cookbook to not crash but its not 100% perfect. when you refresh it goes to first recipe in the cookbook and not the current one that you refreshed on.

Sdp coobook fixes

---

db/SampleRecipes.sql
db/create.sql

Added some files to help better maintain the database. Includes a creation file and some recipe examples generously made by @Zach-schwark

Add db files

---

src/lib/components/menu/CreateMenu.svelte
src/routes/(app)/cookbook/+page.server.ts
src/routes/(app)/cookbook/+page.svelte
src/routes/(app)/cookbook/[cookbook_id]/+page.server.ts

Added better error handling for Create Menu. Now both Title input and Section input cannot be empty.
Also a user cannot create a menu even if the inputs are all empty.
Fixed x overflow scroll for cookbooks and menus

Fix create menu

---

src/lib/components/posts/picture_preview.svelte
src/lib/components/posts/post_preview.svelte
src/lib/components/posts/recipe_preview.svelte
src/routes/(app)/+page.server.ts
src/routes/(app)/+page.svelte
src/routes/(app)/+server.ts
src/routes/(app)/search/+page.svelte
src/routes/api/picture_post/preview/+server.ts
src/routes/api/recipe/preview/+server.ts

add picture post preview
add post preview wrapper component
set up main home past to use post_id and post preview wrapper component
link picture page to picture preview

Picture post preview

---

package-lock.json
src/lib/components/navigation/add_nav.svelte
src/lib/types/picture.type.ts
src/lib/types/recipe.type.ts
src/routes/(app)/picture/new/+page.svelte
src/routes/(app)/picture/new/+server.ts
src/routes/(app)/recipe/new/+page.svelte
src/routes/(app)/recipe/new/+server.ts

added design for Creation of picture post
connected picture post to DB
connected userID to recipe and picture posts

Picture Post Creation

---

src/lib/components/comments/comment_chain.svelte
src/lib/components/comments/post_comments.svelte
src/routes/(app)/picture/[picture_id]/+page.server.ts
src/routes/(app)/picture/[picture_id]/+page.svelte
src/routes/(app)/recipe/[recipe_id]/+page.svelte
src/routes/api/comments/+server.ts
src/routes/api/comments/post/+server.ts

Added comments components
Added comments to posts
Added comments to pictures

Added Comments

---

src/routes/(app)/search/+page.svelte
src/routes/(app)/search/+server.ts

fixed sql statmeent
fixed masonry layout

Fix Search bug

---

src/routes/(app)/+layout.svelte
src/routes/(app)/profile/[user_id]/+page.server.ts
src/routes/(app)/profile/[user_id]/+page.svelte
src/routes/(app)/profile/edit/+page.server.ts
src/routes/(app)/profile/edit/+page.svelte
src/routes/api/user/+server.ts

Fix: Profile bugs and UI updates

Profile fix

---

src/routes/(app)/profile/[user_id]/+page.server.ts
src/routes/(app)/profile/[user_id]/+page.svelte
src/routes/(app)/profile/edit/+page.server.ts
src/routes/(app)/profile/edit/+page.svelte

remove edit username option
fix scroll on user page

issue 49: able to edit username

---

src/lib/components/save_recipe.svelte
src/routes/(app)/picture/new/+page.svelte
src/routes/(app)/recipe/[recipe_id]/+page.svelte
src/routes/(app)/recipe/new/+page.svelte

Fixed buttons so they are all the same
Fixed adding an empty ingredient and instruction

Buttons fix

---

src/routes/(app)/recipe/[recipe_id]/+page.svelte

fix the scroll on recipe viewing page

fix scroll on recipe page

---

src/lib/components/comments/post_comments.svelte

fix: Not logged in users can't comment

---

src/lib/components/cookbooks/SelectCookbook.svelte

add: No cookbooks found in saving recipe text

---

src/lib/components/recipe_of_the_day.svelte

Fixed the image issue. Please let me know if it works on all scrrens

Recipe of day fix

---

src/routes/(signin)/login/+page.svelte

Added feedback on failed login
Fixed bug where the panel would shrink to the side on small screens.

Added login feedback

---

src/routes/(app)/profile/edit/+page.svelte

Add cancel button to edit profile page

---

src/lib/components/previews/picture_preview.svelte
src/lib/components/previews/post_preview.svelte
src/lib/components/previews/recipe_preview.svelte
src/routes/(app)/+page.svelte
src/routes/(app)/picture/[picture_id]/+page.server.ts
src/routes/(app)/picture/[picture_id]/+page.svelte
src/routes/(app)/profile/[user_id]/+page.svelte
src/routes/(app)/recipe/[recipe_id]/+page.server.ts
src/routes/(app)/recipe/[recipe_id]/+page.svelte
src/routes/(app)/search/+page.svelte

fixed #69 
fixed #71 
Switched Recipe & Picture preview to use `{#await}`
Introduced bug where recipe & picture previews with missing information will no longer be shown

Viewing a recipe without a user will not throw a 500 error

---

src/lib/components/delete_collection.svelte
src/routes/(app)/collections/cookbooks/+page.svelte
src/routes/(app)/collections/menus/+page.svelte

add: dialog box to confirm deletion of cookbook or menu

Issue 77 - confirm delete collection

---

src/routes/(app)/collections/cookbooks/+page.server.ts
src/routes/(app)/collections/cookbooks/+page.svelte
src/routes/(app)/cookbook/[cookbook_id]/+page.svelte

Fixed the issue of cancelling the adding of a new cookbook 
Commented out the delete from the actual cookbook -> there are issue after you delete. If u still want it in there, i will fix it. otherwise i dont think its necessary with the delete on the collections page.
fixes #75

Coobook fix

---

src/routes/(signin)/signup/+page.svelte

feedback is added when password is too short.

add: feedback for short password

---

src/routes/api/comments/+server.ts

Loading spinner will not run infinitely anymore, it will just display "No User"
fixes #76

Add error handling on fetching comments

---

package-lock.json
package.json
src/routes/+layout.svelte

Add vercel analytics
Add page speed insights

Add analytics

---

src/routes/(app)/cookbook/[cookbook_id]/+page.server.ts
src/routes/(app)/cookbook/[cookbook_id]/+page.svelte
src/routes/(app)/menu/[menu_id]/+page.server.ts
src/routes/(app)/menu/[menu_id]/+page.svelte
src/routes/(app)/picture/[picture_id]/+page.server.ts
src/routes/(app)/recipe/[recipe_id]/+page.server.ts
src/routes/api/cookbook/recipe/+server.ts
src/routes/api/picture_post/preview/+server.ts
src/routes/api/recipe/preview/+server.ts

replaced all snake case use with camel case and removed a few console logs

clean up: fix camel case and remove console logs

---

src/lib/components/cookbooks/SelectCookbook.svelte

Fixed the drop down selector so that the UI works nicely when a user has many cookbooks to choose from.
The bug still exists. Have not fixed as of yet. #70

Fix: scroll on save recipe for cookbook selector

---

src/routes/api/cookbook/recipe/+server.ts
tests/API/test.ts

add: GET testing
